<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="2.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Src.Application\Src.Application.csproj" />
    <ProjectReference Include="..\Src.Domain\Src.Domain.csproj" />
    <ProjectReference Include="..\Src.Dto\Src.Dto.csproj" />
  </ItemGroup>

</Project>
