// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Src.Infrastructure.Persistance;

#nullable disable

namespace Src.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccountPermissions", b =>
                {
                    b.Property<string>("AccountTypeName")
                        .HasColumnType("text")
                        .HasColumnName("account_type");

                    b.Property<string>("Permission")
                        .HasColumnType("text")
                        .HasColumnName("permission");

                    b.HasKey("AccountTypeName", "Permission");

                    b.HasIndex("Permission");

                    b.ToTable("Account_Permissions", (string)null);
                });

            modelBuilder.Entity("Src.Domain.Entities.AccountType", b =>
                {
                    b.Property<string>("AccountTypeName")
                        .HasColumnType("text")
                        .HasColumnName("account_type");

                    b.HasKey("AccountTypeName");

                    b.ToTable("Account_Type", (string)null);
                });

            modelBuilder.Entity("Src.Domain.Entities.Cart", b =>
                {
                    b.Property<int>("CartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cart_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CartId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_description");

                    b.Property<string>("ItemTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_title");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("integer")
                        .HasColumnName("submission_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("CartId");

                    b.HasIndex("SubmissionId");

                    b.HasIndex(new[] { "Username", "SubmissionId" }, "CartUserSubmissionKey")
                        .IsUnique();

                    b.ToTable("Cart", (string)null);
                });

            modelBuilder.Entity("Src.Domain.Entities.Course", b =>
                {
                    b.Property<int>("SubmissionId")
                        .HasColumnType("integer")
                        .HasColumnName("submission_id");

                    b.Property<string>("CourseName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("course_name");

                    b.Property<string>("CourseType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CourseType");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("image");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<byte[]>("UploadedMaterial")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("uploaded_material");

                    b.HasKey("SubmissionId");

                    b.HasIndex("CourseName")
                        .IsUnique();

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("Src.Domain.Entities.Favourites", b =>
                {
                    b.Property<int>("FavId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("fav_ID");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("FavId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("ItemDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_description");

                    b.Property<string>("ItemTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_title");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("integer")
                        .HasColumnName("submission_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("FavId");

                    b.HasIndex("SubmissionId");

                    b.HasIndex(new[] { "Username", "SubmissionId" }, "FavouritesUserSubmissionKey")
                        .IsUnique();

                    b.ToTable("Favourites", (string)null);
                });

            modelBuilder.Entity("Src.Domain.Entities.IndividualPermissions", b =>
                {
                    b.Property<string>("Permission")
                        .HasColumnType("text")
                        .HasColumnName("permission");

                    b.HasKey("Permission");

                    b.ToTable("Individual_Permissions", (string)null);
                });

            modelBuilder.Entity("Src.Domain.Entities.Merch", b =>
                {
                    b.Property<int>("SubmissionId")
                        .HasColumnType("integer")
                        .HasColumnName("submission_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("image");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<int>("QuantityMax")
                        .HasColumnType("integer")
                        .HasColumnName("qty_max");

                    b.Property<int>("QuantityMin")
                        .HasColumnType("integer")
                        .HasColumnName("qty_min");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision")
                        .HasColumnName("rating");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("size");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("SubmissionId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Merch", (string)null);
                });

            modelBuilder.Entity("Src.Domain.Entities.Newsfeed", b =>
                {
                    b.Property<int>("SubmissionId")
                        .HasColumnType("integer")
                        .HasColumnName("submission_id");

                    b.Property<bool>("Alert")
                        .HasColumnType("boolean")
                        .HasColumnName("alert");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("image");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("SubmissionId");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("NewsFeed", (string)null);
                });

            modelBuilder.Entity("Src.Domain.Entities.Prayers", b =>
                {
                    b.Property<string>("PrayerName")
                        .HasColumnType("text");

                    b.Property<string>("PrayerContent")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prayer_content");

                    b.HasKey("PrayerName");

                    b.ToTable("Prayers", (string)null);
                });

            modelBuilder.Entity("Src.Domain.Entities.PurchaseHistory", b =>
                {
                    b.Property<int>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("transaction_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TransactionId"));

                    b.Property<string>("ItemTitle")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_title");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("item_type");

                    b.Property<double>("Price")
                        .HasColumnType("double precision")
                        .HasColumnName("price");

                    b.Property<DateTime>("PurchaseTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("purchase_timestamp");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<int?>("SubmissionId")
                        .HasColumnType("integer")
                        .HasColumnName("submission_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("TransactionId");

                    b.HasIndex("SubmissionId");

                    b.HasIndex("Username");

                    b.ToTable("Purchase_History", (string)null);
                });

            modelBuilder.Entity("Src.Domain.Entities.Review", b =>
                {
                    b.Property<int>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("review_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReviewId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("modified_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<int>("SubmissionId")
                        .HasColumnType("integer")
                        .HasColumnName("submission_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("ReviewId");

                    b.HasIndex("SubmissionId");

                    b.HasIndex("Username");

                    b.ToTable("Review", (string)null);
                });

            modelBuilder.Entity("Src.Domain.Entities.SikhEvent", b =>
                {
                    b.Property<int>("SubmissionId")
                        .HasColumnType("integer")
                        .HasColumnName("submission_id");

                    b.Property<string>("ContactInfo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contact_info");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime>("EventDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("event_date_time");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("image");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("location");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("SubmissionId");

                    b.ToTable("Sikh_Event", (string)null);
                });

            modelBuilder.Entity("Src.Domain.Entities.Submission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("submission_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SubmissionId"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("DateSubmitted")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date_submitted");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("SubmissionId");

                    b.HasIndex("Username");

                    b.ToTable("Submission", (string)null);
                });

            modelBuilder.Entity("Src.Domain.Entities.Temples", b =>
                {
                    b.Property<int>("TempleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("temple_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TempleId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<float>("lat")
                        .HasColumnType("real")
                        .HasColumnName("lat");

                    b.Property<float>("lon")
                        .HasColumnType("real")
                        .HasColumnName("lon");

                    b.HasKey("TempleId");

                    b.ToTable("Temples", (string)null);
                });

            modelBuilder.Entity("Src.Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("AccountTypeName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("HashedPass")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hashed_pass");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("UserId");

                    b.HasIndex("AccountTypeName");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("User", (string)null);
                });

            modelBuilder.Entity("AccountPermissions", b =>
                {
                    b.HasOne("Src.Domain.Entities.AccountType", "AccountType")
                        .WithMany("AccountPermissions")
                        .HasForeignKey("AccountTypeName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Src.Domain.Entities.IndividualPermissions", "IndividualPermissions")
                        .WithMany("AccountPermissions")
                        .HasForeignKey("Permission")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountType");

                    b.Navigation("IndividualPermissions");
                });

            modelBuilder.Entity("Src.Domain.Entities.Cart", b =>
                {
                    b.HasOne("Src.Domain.Entities.Submission", "Submission")
                        .WithMany("Carts")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Src.Domain.Entities.User", "User")
                        .WithMany("Carts")
                        .HasForeignKey("Username")
                        .HasPrincipalKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Src.Domain.Entities.Course", b =>
                {
                    b.HasOne("Src.Domain.Entities.Submission", "Submission")
                        .WithOne("Course")
                        .HasForeignKey("Src.Domain.Entities.Course", "SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Src.Domain.Entities.Favourites", b =>
                {
                    b.HasOne("Src.Domain.Entities.Submission", "Submission")
                        .WithMany("Favourites")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Src.Domain.Entities.User", "User")
                        .WithMany("Favourites")
                        .HasForeignKey("Username")
                        .HasPrincipalKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Src.Domain.Entities.Merch", b =>
                {
                    b.HasOne("Src.Domain.Entities.Submission", "Submission")
                        .WithOne("Merch")
                        .HasForeignKey("Src.Domain.Entities.Merch", "SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Src.Domain.Entities.Newsfeed", b =>
                {
                    b.HasOne("Src.Domain.Entities.Submission", "Submission")
                        .WithOne("Newsfeed")
                        .HasForeignKey("Src.Domain.Entities.Newsfeed", "SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Src.Domain.Entities.PurchaseHistory", b =>
                {
                    b.HasOne("Src.Domain.Entities.Submission", "Submission")
                        .WithMany("PurchaseHistory")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Src.Domain.Entities.User", "User")
                        .WithMany("PurchaseHistories")
                        .HasForeignKey("Username")
                        .HasPrincipalKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Src.Domain.Entities.Review", b =>
                {
                    b.HasOne("Src.Domain.Entities.Submission", "Submission")
                        .WithMany("Reviews")
                        .HasForeignKey("SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Src.Domain.Entities.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("Username")
                        .HasPrincipalKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Src.Domain.Entities.SikhEvent", b =>
                {
                    b.HasOne("Src.Domain.Entities.Submission", "Submission")
                        .WithOne("SikhEvent")
                        .HasForeignKey("Src.Domain.Entities.SikhEvent", "SubmissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Submission");
                });

            modelBuilder.Entity("Src.Domain.Entities.Submission", b =>
                {
                    b.HasOne("Src.Domain.Entities.User", "User")
                        .WithMany("Submissions")
                        .HasForeignKey("Username")
                        .HasPrincipalKey("Username")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Src.Domain.Entities.User", b =>
                {
                    b.HasOne("Src.Domain.Entities.AccountType", "AccountType")
                        .WithMany("Users")
                        .HasForeignKey("AccountTypeName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccountType");
                });

            modelBuilder.Entity("Src.Domain.Entities.AccountType", b =>
                {
                    b.Navigation("AccountPermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Src.Domain.Entities.IndividualPermissions", b =>
                {
                    b.Navigation("AccountPermissions");
                });

            modelBuilder.Entity("Src.Domain.Entities.Submission", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Course");

                    b.Navigation("Favourites");

                    b.Navigation("Merch");

                    b.Navigation("Newsfeed");

                    b.Navigation("PurchaseHistory");

                    b.Navigation("Reviews");

                    b.Navigation("SikhEvent");
                });

            modelBuilder.Entity("Src.Domain.Entities.User", b =>
                {
                    b.Navigation("Carts");

                    b.Navigation("Favourites");

                    b.Navigation("PurchaseHistories");

                    b.Navigation("Reviews");

                    b.Navigation("Submissions");
                });
#pragma warning restore 612, 618
        }
    }
}
